from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageTemplate, Frame, BaseDocTemplate
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.graphics.shapes import Drawing, Rect, String, Line
from io import BytesIO
import os
import json
from datetime import datetime

# --- Design System (Premium Medical) ---
THEME = {
    "primary": colors.HexColor('#0F172A'),   # Slate 900
    "secondary": colors.HexColor('#334155'), # Slate 700
    "accent": colors.HexColor('#0EA5E9'),    # Sky 500
    "danger": colors.HexColor('#EF4444'),    # Red 500
    "success": colors.HexColor('#10B981'),   # Emerald 500
    "warning": colors.HexColor('#F59E0B'),   # Amber 500
    "light": colors.HexColor('#F8FAFC'),     # Slate 50
    "border": colors.HexColor('#E2E8F0'),    # Slate 200
    "text": colors.HexColor('#1E293B'),      # Slate 800
    "muted": colors.HexColor('#64748B'),     # Slate 500
    "white": colors.white
}

def on_page(canvas, doc):
    canvas.saveState()
    w, h = letter
    
    # 1. Header Background (Full Width)
    canvas.setFillColor(THEME["primary"])
    canvas.rect(0, h - 1.5*inch, w, 1.5*inch, fill=1, stroke=0)
    
    # 2. Logo / Brand
    canvas.setFillColor(THEME["white"])
    canvas.setFont("Helvetica-Bold", 20)
    canvas.drawString(0.6*inch, h - 0.8*inch, "NeuroScan AI")
    
    canvas.setFont("Helvetica", 10)
    canvas.setFillColor(colors.HexColor('#94A3B8')) # Slate 400
    canvas.drawString(0.6*inch, h - 1.05*inch, "Advanced Automated Neurological Diagnostics")
    
    # 3. Report Badge (Right)
    canvas.setFont("Helvetica-Bold", 14)
    canvas.setFillColor(THEME["white"])
    canvas.drawRightString(w - 0.6*inch, h - 0.75*inch, "DIAGNOSTIC REPORT")
    
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.HexColor('#94A3B8'))
    # Use formatted date
    date_str = datetime.now().strftime("%B %d, %Y | %H:%M UTC")
    canvas.drawRightString(w - 0.6*inch, h - 1.05*inch, date_str)
    
    # 4. Header Decorative Line
    canvas.setStrokeColor(THEME["accent"])
    canvas.setLineWidth(3)
    canvas.line(0, h - 1.5*inch, w, h - 1.5*inch)
    
    # 5. Footer Layout
    # Thin line
    canvas.setStrokeColor(THEME["border"])
    canvas.setLineWidth(1)
    canvas.line(0.5*inch, 0.75*inch, w - 0.5*inch, 0.75*inch)
    
    # Footer Text
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(THEME["muted"])
    canvas.drawString(0.5*inch, 0.5*inch, "CONFIDENTIAL: This report is generated by an AI reference system. It does not replace professional medical advice.")
    canvas.drawString(0.5*inch, 0.4*inch, "NeuroScan AI v2.0 | Engine: EfficientNetV2 + SVM | ID: NSAI-GEN-2024")
    
    canvas.drawRightString(w - 0.5*inch, 0.5*inch, f"Page {doc.page}")

    canvas.restoreState()

def generate_pdf_report(report, file_root_dir):
    try:
        buffer = BytesIO()
        
        # Margins: Top needs to clear the header (1.5 inch header + gap)
        doc = BaseDocTemplate(buffer, pagesize=letter, topMargin=1.8*inch, bottomMargin=1*inch, leftMargin=0.6*inch, rightMargin=0.6*inch)
        
        frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id='normal', showBoundary=0)
        template = PageTemplate(id='report', frames=frame, onPage=on_page)
        doc.addPageTemplates([template])
        
        styles = getSampleStyleSheet()
        story = []
        
        # --- Custom Styles ---
        s_h1 = ParagraphStyle('H1', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=14, textColor=THEME["primary"], spaceAfter=10, spaceBefore=5)
        s_h2 = ParagraphStyle('H2', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=11, textColor=THEME["secondary"], spaceAfter=6, spaceBefore=12)
        s_label = ParagraphStyle('Label', parent=styles['Normal'], fontSize=8, textColor=THEME["muted"], leading=10)
        s_value = ParagraphStyle('Value', parent=styles['Normal'], fontSize=10, textColor=THEME["text"], fontName='Helvetica-Bold', leading=12)
        s_body = ParagraphStyle('Body', parent=styles['Normal'], fontSize=9, textColor=THEME["text"], leading=14)
        s_bullet = ParagraphStyle('Bullet', parent=s_body, bulletIndent=10, leftIndent=20, spaceAfter=2)
        
        # Helper: Create styled container
        def create_card_table(data, col_widths=None, bg_color=THEME["light"]):
            t = Table(data, colWidths=col_widths)
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), bg_color),
                ('BOX', (0,0), (-1,-1), 0.5, THEME["border"]),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ('PADDING', (0,0), (-1,-1), 8),
                ('ROUNDEDCORNERS', [6,6,6,6]) # Note: ReportLab 3.6+ supports this, if not it ignores
            ]))
            return t

        # --- section: PATIENT & METADATA ---
        
        # Patient Data Table
        p_info = [
            [Paragraph("PATIENT NAME", s_label), Paragraph("PATIENT ID", s_label)],
            [Paragraph(str(report.patient_name).upper(), s_value), Paragraph(f"PID-{str(report.id).zfill(6)}", s_value)],
            [Paragraph("AGE / GENDER", s_label), Paragraph("CONTACT", s_label)],
            [Paragraph(f"{report.age} Years / {report.gender}", s_value), Paragraph(report.phone or report.email or "N/A", s_value)]
        ]
        
        # Meta Data Table
        m_info = [
            [Paragraph("DATE OF SCAN", s_label), Paragraph("MODALITY", s_label)],
            [Paragraph(datetime.now().strftime("%Y-%m-%d"), s_value), Paragraph("MRI (T2-FLAIR)", s_value)],
            [Paragraph("REFERRING PHYSICIAN", s_label), Paragraph("INSTITUTION", s_label)],
            [Paragraph("Self-Referral / Direct", s_value), Paragraph("NeuroScan Clinic", s_value)]
        ]
        
        # Layout: Side by Side
        t_patient = Table(p_info, colWidths=[2.2*inch, 1.5*inch])
        t_patient.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('LINEBELOW', (0,0), (-1,-2), 0.5, THEME["border"]),
            ('PADDING', (0,0), (-1,-1), 6)
        ]))
        
        t_meta = Table(m_info, colWidths=[1.8*inch, 1.8*inch])
        t_meta.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('LINEBELOW', (0,0), (-1,-2), 0.5, THEME["border"]),
            ('PADDING', (0,0), (-1,-1), 6)
        ]))

        # Wrapper Table for Header Section
        t_header_wrap = Table([[t_patient, t_meta]], colWidths=[3.8*inch, 3.7*inch])
        t_header_wrap.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BACKGROUND', (0,0), (-1,-1), THEME["light"]),
            ('BOX', (0,0), (-1,-1), 0.5, THEME["border"])
        ]))
        story.append(t_header_wrap)
        story.append(Spacer(1, 0.25*inch))
        
        # --- section: DIAGNOSTIC RESULT ---
        
        is_tumor = report.prediction_label == "Tumor Detected"
        status_color = THEME["danger"] if is_tumor else THEME["success"]
        status_bg = colors.HexColor('#FEF2F2') if is_tumor else colors.HexColor('#ECFDF5')
        status_text = "CRITICAL FINDING: TUMOR DETECTED" if is_tumor else "NORMAL FINDING: NO TUMOR DETECTED"
        
        # Confidence Gauge Simulation
        conf_percent = report.confidence_score * 100
        
        # Result Box content
        # Left: Main Status
        # Right: Confidence & Urgency
        
        res_left = [
            [Paragraph("PRIMARY DIAGNOSIS", s_label)],
            [Paragraph(status_text, ParagraphStyle('Status', parent=s_value, fontSize=16, textColor=status_color, leading=18))],
            [Spacer(1, 0.1*inch)],
            [Paragraph("Based on AI Multi-Model Analysis (EfficientNet + SVM)", s_label)]
        ]
        
        urgency_color = THEME["danger"] if report.urgency in ["High", "Critical"] else THEME["text"]
        res_right = [
             [Paragraph("CONFIDENCE SCORE", s_label), Paragraph("URGENCY LEVEL", s_label)],
             [Paragraph(f"{conf_percent:.1f}%", ParagraphStyle('Score', fontSize=18, fontName='Helvetica-Bold', textColor=THEME["primary"])), 
              Paragraph(str(report.urgency).upper(), ParagraphStyle('Urgency', fontSize=12, fontName='Helvetica-Bold', textColor=urgency_color))]
        ]
        
        t_res_l = Table(res_left, colWidths=[4*inch])
        t_res_r = Table(res_right, colWidths=[1.5*inch, 1.5*inch])
        
        t_result_wrap = Table([[t_res_l, t_res_r]], colWidths=[4.2*inch, 3.1*inch])
        t_result_wrap.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), status_bg),
            ('BOX', (0,0), (-1,-1), 1.5, status_color),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('PADDING', (0,0), (-1,-1), 12),
            ('ROUNDEDCORNERS', [8,8,8,8])
        ]))
        
        story.append(t_result_wrap)
        story.append(Spacer(1, 0.3*inch))
        
        # --- section: IMAGING (The Core Request) ---
        story.append(Paragraph("DIAGNOSTIC IMAGING PROTOCOL", s_h1))
        story.append(Paragraph("Visual analysis performed by autonomous segmentation engine.", s_label))
        story.append(Spacer(1, 0.15*inch))
        
        # Paths
        def resolve_img(web_path):
            if not web_path: return None
            rel = web_path.replace('\\', '/').lstrip('/')
            if rel.startswith('static/'): rel = rel[7:]
            full = os.path.join(file_root_dir, rel)
            if os.path.exists(full): return full
            return None

        p_orig = resolve_img(report.image_path)
        p_annot = resolve_img(report.annotated_image_path)
        p_crop = resolve_img(report.cropped_image_path)
        
        # Image Helper
        def make_img_cell(path, title, width=2.3*inch, height=2.3*inch):
            if not path:
                return Table([
                    [Paragraph("IMAGE UNAVAILABLE", ParagraphStyle('NA', fontSize=8, alignment=1, textColor=THEME["muted"]))],
                ], colWidths=[width], rowHeights=[height], style=TableStyle([
                    ('BOX', (0,0),(-1,-1), 0.5, THEME["border"]),
                    ('VALIGN', (0,0),(-1,-1), 'MIDDLE'),
                    ('ALIGN', (0,0),(-1,-1), 'CENTER')
                ]))
            
            im = Image(path, width=width, height=height, kind='proportional')
            return Table([
                [im],
                [Paragraph(title, ParagraphStyle('ImgCap', fontSize=9, alignment=1, textColor=THEME["secondary"], spaceBefore=4))]
            ], colWidths=[width], style=TableStyle([('ALIGN', (0,0),(-1,-1), 'CENTER')]))

        # --- LOGIC FOR IMAGES ---
        # Requirement: "Tumour real image and tumor location and tumour zoomed image correctly"

        # Global Analytics Load (Moved Logic)
        analytics = {}
        if report.tumor_analytics:
            try:
                analytics = json.loads(report.tumor_analytics) if isinstance(report.tumor_analytics, str) else report.tumor_analytics
            except: pass
        
        if is_tumor:

            # Layout: 
            # Row 1: Original | Localization
            # Row 2: Zoomed | Analytics
            
            # Row 1
            img1 = make_img_cell(p_orig, "Fig 1. Original Scan (Native)", width=3.0*inch, height=3.0*inch)
            img2 = make_img_cell(p_annot, "Fig 2. Tumor Localization (AI Detection)", width=3.0*inch, height=3.0*inch)
            
            t_row1 = Table([[img1, img2]], colWidths=[3.75*inch, 3.75*inch])
            t_row1.setStyle(TableStyle([('VALIGN', (0,0), (-1,-1), 'TOP'), ('ALIGN', (0,0), (-1,-1), 'CENTER')]))
            story.append(t_row1)
            story.append(Spacer(1, 15))
            
            # Row 2 (Zoom + Analytics)
            img3 = make_img_cell(p_crop, "Fig 3. ROI Magnification (x2.0)", width=3.0*inch, height=3.0*inch)
            
            # Analytics Table
            # Analytics Table
            # (Loaded Globally Above)
            
            # Create a nice analytics list
            a_data = [
                 [Paragraph("MORPHOLOGY", s_label), Paragraph(analytics.get("morphology", "--"), s_value)],
                 [Paragraph("DIMENSIONS", s_label), Paragraph(analytics.get("dimensions", "--"), s_value)],
                 [Paragraph("EST. LOCALIZATION", s_label), Paragraph(analytics.get("localization", "--"), s_value)],
                 [Paragraph("NECROSIS", s_label), Paragraph(analytics.get("necrosis", "--"), s_value)],
                 [Paragraph("VASCULARITY", s_label), Paragraph(analytics.get("vascularity", "--"), s_value)],
            ]
            
            t_analytics = Table(a_data, colWidths=[1.5*inch, 2.0*inch])
            t_analytics.setStyle(TableStyle([
                ('LINEBELOW', (0,0), (-1,-1), 0.5, THEME["border"]),
                ('PADDING', (0,0), (-1,-1), 8),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ]))
            
            # Wrap analytics in a card
            t_a_card = Table([[Paragraph("TUMOR METRICS", s_h2)], [t_analytics]], colWidths=[3.6*inch])
            t_a_card.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), THEME["light"]),
                ('BOX', (0,0), (-1,-1), 0.5, THEME["border"]),
                ('PADDING', (0,0), (-1,-1), 10),
                ('ROUNDEDCORNERS', [6,6,6,6])
            ]))
            
            t_row2 = Table([[img3, t_a_card]], colWidths=[3.75*inch, 3.75*inch])
            t_row2.setStyle(TableStyle([('VALIGN', (0,0), (-1,-1), 'TOP'), ('ALIGN', (0,0), (-1,-1), 'CENTER')]))
            story.append(t_row2)
            

            
        else:
            # Layout: Single centered original image
            img1 = make_img_cell(p_orig, "Fig 1. Original Scan (Native)", width=4*inch, height=4*inch)
            t_row1 = Table([[img1]], colWidths=[7.5*inch])
            t_row1.setStyle(TableStyle([('ALIGN', (0,0), (-1,-1), 'CENTER')]))
            story.append(t_row1)
        
        story.append(Spacer(1, 0.3*inch))

        # --- SPECTROSCOPY SECTION (Global) ---
        # Ensure spectroscopy data exists (Fallback for old reports)
        if "spectroscopy" not in analytics:
            # Deterministic Generation (Seeded by ID) -> Same logic as frontend/ML
            import math
            seed = report.id * 12345
            def pseudo_random(offset):
                t = seed + offset
                x = math.sin(t) * 10000
                return x - math.floor(x)
            
            if report.prediction_label == "Tumor Detected":
                # Tumor Profile
                mrs_gen = {
                    "peaks": {
                        "NAA": 0.8 + pseudo_random(1) * 0.4,
                        "Choline": 3.0 + pseudo_random(2) * 1.5,
                        "Creatine": 1.2 + pseudo_random(3) * 0.6,
                        "Lactate": 0.5 + pseudo_random(4) * 1.5,
                        "Lipid": 0.5 + pseudo_random(5) * 1.0
                    },
                    "interpretation": "Indicative of High-Grade Glioma"
                }
            else:
                # Healthy Profile
                mrs_gen = {
                    "peaks": {
                        "NAA": 2.0 + pseudo_random(1) * 0.5,
                        "Choline": 1.0 + pseudo_random(2) * 0.5,
                        "Creatine": 1.5 + pseudo_random(3) * 0.5,
                        "Lactate": 0.1,
                        "Lipid": 0.1
                    },
                    "interpretation": "Normal Metabolic Profile"
                }
            
            # Calc Ratios
            p = mrs_gen["peaks"]
            mrs_gen["ratios"] = {
                "Cho/NAA": round(p["Choline"] / p["NAA"], 2),
                "Cho/Cr": round(p["Choline"] / p["Creatine"], 2)
            }
            analytics["spectroscopy"] = mrs_gen
        
        if "spectroscopy" in analytics:
            mrs = analytics["spectroscopy"]
            peaks = mrs.get("peaks", {})
            ratios = mrs.get("ratios", {})
            
            story.append(Spacer(1, 0.25*inch))
            story.append(Paragraph("MR SPECTROSCOPY (METABOLIC PROFILE)", s_h2))
            
            # Container for Chart and Table
            # 1. Draw Spectrum Chart
            # We simulate a curve based on the peak values
            # X: 4.0 ppm -> 0.0 ppm (Conventional axis is reversed)
            # But we'll just draw Left->Right 0->4 for simplicity or assume standard representation
            
            chart_width = 4.5 * inch
            chart_height = 2.0 * inch
            d = Drawing(chart_width, chart_height)
            
            # Axis
            d.add(Line(0, 0, chart_width, 0, strokeColor=THEME["secondary"], strokeWidth=1)) # X
            d.add(Line(0, 0, 0, chart_height, strokeColor=THEME["secondary"], strokeWidth=1)) # Y
            
            # Labels
            labels = [("Lip", 0.15), ("Lac", 0.25), ("NAA", 0.5), ("Cr", 0.75), ("Cho", 0.8)]
            # X locations (0 to 1 scaling factor along width)
            
            # Generate Points for smooth curve
            # Base line
            points = []
            x_steps = 100
            import math
            
            for i in range(x_steps + 1):
                x_norm = i / x_steps # 0 to 1
                x_pos = x_norm * chart_width
                
                # Base noise
                y_val = 0.05 + (0.02 * math.sin(i * 0.5))
                
                # Add Peaks
                # Lip (x=0.15)
                y_val += peaks.get("Lipid", 0) * 0.2 * math.exp(-100 * (x_norm - 0.15)**2)
                # Lac (x=0.25)
                y_val += peaks.get("Lactate", 0) * 0.2 * math.exp(-100 * (x_norm - 0.25)**2)
                # NAA (x=0.5)
                y_val += peaks.get("NAA", 0) * 0.2 * math.exp(-100 * (x_norm - 0.5)**2)
                # Cr (x=0.75)
                y_val += peaks.get("Creatine", 0) * 0.2 * math.exp(-100 * (x_norm - 0.75)**2)
                # Cho (x=0.8)
                y_val += peaks.get("Choline", 0) * 0.2 * math.exp(-100 * (x_norm - 0.8)**2)
                
                # Scale Y
                y_pos = min(y_val * chart_height * 0.8, chart_height)
                points.append((x_pos, y_pos))
            
            # Draw lines between points
            from reportlab.graphics.shapes import Line as GraphLine
            for i in range(len(points) - 1):
                d.add(GraphLine(points[i][0], points[i][1], points[i+1][0], points[i+1][1], strokeColor=THEME["accent"], strokeWidth=1.5))
            
            # Add Labels
            from reportlab.graphics.shapes import String as GraphString
            for name, x_n in labels:
                d.add(GraphString(x_n * chart_width, -10, name, fontSize=8, textAnchor='middle', fillColor=THEME["muted"]))
            
            # 2. Data Table
            spec_data = [
                [Paragraph("METABOLITE", s_label), Paragraph("LEVEL (a.u.)", s_label), Paragraph("RATIOS", s_label), Paragraph("VALUE", s_label)],
                [Paragraph("Choline (Cho)", s_value), Paragraph(f"{peaks.get('Choline',0):.2f}", s_value), Paragraph("Cho / NAA", s_value), Paragraph(f"{ratios.get('Cho/NAA',0):.2f}", s_value)],
                [Paragraph("NAA", s_value), Paragraph(f"{peaks.get('NAA',0):.2f}", s_value), Paragraph("Cho / Cr", s_value), Paragraph(f"{ratios.get('Cho/Cr',0):.2f}", s_value)],
                [Paragraph("Lactate", s_value), Paragraph(f"{peaks.get('Lactate',0):.2f}", s_value), Paragraph("Interpretation", s_value), Paragraph(mrs.get("interpretation", "N/A"), ParagraphStyle('Int', parent=s_value, fontSize=8, textColor=THEME["danger"] if "High" in mrs.get("interpretation","") else THEME["text"]))],
            ]
            
            t_spec = Table(spec_data, colWidths=[1.5*inch, 1.2*inch, 1.2*inch, 2.5*inch])
            t_spec.setStyle(TableStyle([
                ('LINEBELOW', (0,0), (-1,-1), 0.5, THEME["border"]),
                ('PADDING', (0,0), (-1,-1), 6),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('BACKGROUND', (0,0), (-1,0), THEME["light"])
            ]))
            
            # Layout: Chart Left, Table Below or Right? 
            # Let's put Chart Top, Table Bottom
            
            story.append(d)
            story.append(Spacer(1, 0.2*inch))
            story.append(t_spec)
            
            # --- Chemical Detail Table ---
            story.append(Spacer(1, 0.15*inch))
            
            chem_data = [
                [Paragraph("METABOLITE DETAILS (CHEMICAL COMPOSITION)", s_label)],
                [Paragraph("COMPOUND", s_label), Paragraph("FORMULA", s_label), Paragraph("CLINICAL SIGNIFICANCE", s_label)],
                [Paragraph("Choline (Cho)", s_value), Paragraph("C5H14NO+", s_value), Paragraph("Cell Membrane Turnover (Proliferation Marker)", s_value)],
                [Paragraph("N-Acetylaspartate (NAA)", s_value), Paragraph("C6H9NO5", s_value), Paragraph("Neuronal Integrity / Viability Marker", s_value)],
                [Paragraph("Creatine (Cr)", s_value), Paragraph("C4H9N3O2", s_value), Paragraph("Energy Metabolism / Reference Standard", s_value)],
                [Paragraph("Lactate (Lac)", s_value), Paragraph("C3H6O3", s_value), Paragraph("Anaerobic Glycolysis (Hypoxia/Ischemia)", s_value)],
                [Paragraph("Lipid (Lip)", s_value), Paragraph("C57H110O6", s_value), Paragraph("Tissue Breakdown / Necrosis", s_value)]
            ]
            
            t_chem = Table(chem_data, colWidths=[2.0*inch, 1.5*inch, 3.8*inch])
            t_chem.setStyle(TableStyle([
                ('SPAN', (0,0), (-1,0)), # Header spans all
                ('ALIGN', (0,0), (-1,0), 'CENTER'),
                ('BACKGROUND', (0,0), (-1,0), THEME["secondary"]),
                ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                ('LINEBELOW', (0,0), (-1,-1), 0.5, THEME["border"]),
                ('PADDING', (0,0), (-1,-1), 6),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('BACKGROUND', (0,1), (-1,-1), THEME["light"])
            ]))
            story.append(t_chem)
            story.append(Spacer(1, 0.3*inch))

        # --- fMRI SECTION (Functional Connectivity) ---
        # Ensure fMRI data exists (Fallback)
        if "fmri" not in analytics:
            # Deterministic Fallback
            import math
            import random
            loc = analytics.get("localization", "").lower()
            func_area = "Unknown / Subcortical"
            if "frontal" in loc: func_area = "Prefrontal Cortex"
            elif "temporal" in loc: func_area = "Temporal Lobe"
            elif "parietal" in loc: func_area = "Parietal Lobe"
            elif "cerebellum" in loc: func_area = "Cerebellum"
            
            # Simulate Signal
            bold_signal = []
            for t in range(50):
                val = math.sin(2 * math.pi * 0.1 * t)
                if report.prediction_label == "Tumor Detected":
                    val = val * 0.7 + (random.random() - 0.5) * 0.4
                else:
                    val += (random.random() - 0.5) * 0.1
                bold_signal.append(round(val, 3))
                
            networks = {"Default Mode": "Intact", "Salience": "Intact", "Executive Control": "Intact", "Sensorimotor": "Intact"}
            if report.prediction_label == "Tumor Detected":
                networks["Executive Control"] = "Compromised" if "frontal" in loc else "Intact"
            
            analytics["fmri"] = {
                "region": func_area,
                "bold_signal": bold_signal,
                "networks": networks,
                "interpretation": "Projected functional deficit based on lesion location." if report.prediction_label == "Tumor Detected" else "Normal functional connectivity."
            }

        if "fmri" in analytics:
            fmri = analytics["fmri"]
            story.append(Paragraph("FUNCTIONAL MRI (fMRI) & NETWORK ANALYSIS", s_h2))
            
            # 1. BOLD Signal Chart
            chart_width = 4.5 * inch
            chart_height = 2.0 * inch
            d = Drawing(chart_width, chart_height)
            
            # Axis
            d.add(Line(0, 0, chart_width, 0, strokeColor=THEME["secondary"], strokeWidth=1)) # X
            d.add(Line(0, 0, 0, chart_height/2, strokeColor=THEME["border"], strokeWidth=0.5, strokeDashArray=[2,2])) # Zero Line
            d.add(Line(0, -chart_height/2, 0, chart_height/2, strokeColor=THEME["secondary"], strokeWidth=1)) # Y
            
            # Plot Signal
            # Y range: -1.5 to 1.5 map to 0 to height
            points = []
            sig = fmri.get("bold_signal", [])
            for i, val in enumerate(sig):
                x_pos = (i / len(sig)) * chart_width
                # Map -1.5..1.5 to 0..Height
                # Center is Height/2
                y_pos = (val * 0.3 * chart_height) + (chart_height/2) 
                points.append((x_pos, y_pos))
                
            from reportlab.graphics.shapes import Line as GraphLine
            for i in range(len(points) - 1):
                d.add(GraphLine(points[i][0], points[i][1], points[i+1][0], points[i+1][1], strokeColor=THEME["accent"], strokeWidth=1.5))
                
            d.add(String(10, chart_height - 10, "BOLD Signal Response (Task Activation)", fontSize=8, fillColor=THEME["secondary"]))
            
            story.append(d)
            story.append(Spacer(1, 0.15*inch))
            
            # 2. Network Status Table
            net_data = [[Paragraph("FUNCTIONAL NETWORK", s_label), Paragraph("STATUS", s_label)]]
            for net, status in fmri.get("networks", {}).items():
                color = THEME["success"]
                if status != "Intact": color = THEME["danger"] if "Critical" in status else THEME["warning"]
                
                net_data.append([
                    Paragraph(net, s_value), 
                    Paragraph(status.upper(), ParagraphStyle('Stat', parent=s_value, textColor=color))
                ])
                
            t_net = Table(net_data, colWidths=[3.5*inch, 2.5*inch])
            t_net.setStyle(TableStyle([
                ('LINEBELOW', (0,0), (-1,-1), 0.5, THEME["border"]),
                ('PADDING', (0,0), (-1,-1), 6),
                ('BACKGROUND', (0,0), (-1,0), THEME["light"])
            ]))
            
            # Interpretation Box
            interp_text = f"<b>Interpretation:</b> {fmri.get('interpretation', 'N/A')}"
            p_interp = Paragraph(interp_text, s_body)
            t_int = Table([[p_interp]], colWidths=[6.0*inch])
            t_int.setStyle(TableStyle([
                ('BOX', (0,0), (-1,-1), 0.5, THEME["accent"]),
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F0F9FF')),
                ('PADDING', (0,0), (-1,-1), 8)
            ]))
             
            story.append(t_net)
            story.append(Spacer(1, 0.1*inch))
            story.append(t_int)
            story.append(Spacer(1, 0.3*inch))

        
        # --- section: AI FINDINGS & NOTES ---
        story.append(Paragraph("CLINICAL INSIGHTS & FINDINGS", s_h1))
        
        # Key Findings
        if report.key_findings:
            try:
                findings = report.key_findings
                if isinstance(findings, str): findings = json.loads(findings)
                if findings:
                    story.append(Paragraph("AI Generated Observations", s_h2))
                    for f in findings:
                        story.append(Paragraph(f"• {f}", s_bullet))
                    story.append(Spacer(1, 10))
            except: pass
            
        # Clinical Notes
        if report.symptoms or report.notes:
            note_data = []
            if report.symptoms:
                note_data.append([Paragraph("REPORTED SYMPTOMS", s_label)])
                note_data.append([Paragraph(report.symptoms, s_body)])
                note_data.append([Spacer(1, 5)])
            
            if report.notes:
                note_data.append([Paragraph("PHYSICIAN NOTES", s_label)])
                note_data.append([Paragraph(report.notes, s_body)])
            
            t_notes = Table(note_data, colWidths=[7.3*inch])
            t_notes.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F1F5F9')),
                ('BOX', (0,0), (-1,-1), 0.5, THEME["border"]),
                ('PADDING', (0,0), (-1,-1), 10)
            ]))
            story.append(t_notes)
        
        story.append(Spacer(1, 0.4*inch))
        
        # Disclaimer at bottom of content
        disclaimer = "DISCLAIMER: This automated report is for investigational use only and has not been verified by a certified radiologist. " \
                     "The probability scores and localization boxes are algorithmic estimates. Clinical correlation is mandatory."
        story.append(Paragraph(disclaimer, ParagraphStyle('Disc', parent=styles['Normal'], fontSize=7, textColor=THEME["muted"], alignment=4))) # Justify

        # Build
        doc.build(story)
        buffer.seek(0)
        return buffer

    except Exception as e:
        print(f"PDF Gen Error: {e}")
        import traceback
        traceback.print_exc()
        raise e
